drop table Products if exists
drop table ProductTypes if exists
drop table Taxes if exists
drop table ImportTaxes if exists
create table Products (product_id bigint generated by default as identity unique, product_type bigint not null, import_tax bigint not null, description varchar(255) not null unique, price decimal(20,2) not null, primary key (product_id))
create table ProductTypes (product_type_id bigint generated by default as identity unique, description varchar(255) not null unique, tax bigint, primary key (product_type_id))
create table Taxes (tax_id bigint generated by default as identity unique, tax_value decimal(20,2) not null, description varchar(255) not null unique, primary key (tax_id))
create table ImportTaxes (import_tax_id bigint generated by default as identity unique, import_tax_value decimal(20,2) not null, description varchar(255) not null unique, primary key (import_tax_id))
alter table Products add constraint product_to_product_type foreign key (product_type) references ProductTypes
alter table Products add constraint product_to_import_tax foreign key (import_tax) references ImportTaxes
alter table ProductTypes add constraint product_type_to_tax foreign key (tax) references Taxes